//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEL.DATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoSEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EstadoSEL()
        {
            this.SolicitudSEL = new HashSet<SolicitudSEL>();
        }
    
        public decimal IdEstadoSEL { get; set; }
        public string NombreEstadoSEL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudSEL> SolicitudSEL { get; set; }
    }
}
