//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEL.DATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudSEL
    {
        public decimal IdSolicitudSEL { get; set; }
        public decimal IdUsuarioSEL { get; set; }
        public decimal IdEstadoSEL { get; set; }
        public System.DateTime FechaHoraSolicitud { get; set; }
        public Nullable<System.DateTime> FechaHoraConfirmacion { get; set; }
        public Nullable<System.DateTime> FechaHoraCancelacion { get; set; }
        public Nullable<System.DateTime> FechaHoraFinalizacion { get; set; }
        public decimal IdServicioSEL { get; set; }
    
        public virtual EstadoSEL EstadoSEL { get; set; }
        public virtual ServicioSEL ServicioSEL { get; set; }
        public virtual UsuarioSEL UsuarioSEL { get; set; }
    }
}
